Schema and data update
alexansaa/vet_sql pull request #2
Opened 2023-10-03 14:41 UTC by alexansaa

In this milestone, the following features have been implemented:
- Animals table schema update, adding a new column
- Added more data to the table of animals
- Created transactions for different purposes
- Created queries to retrieve specific information regarding questions about data

-- Inside a transaction update the animals table by setting the species column to unspecified. Verify that the change was made.
![image](https://github.com/alexansaa/vet_sql/assets/60579598/b055ee05-b6e8-47f3-a622-b48fe192805a)
--Then roll back the change and verify that the species columns went back to the state before the transaction.
![image](https://github.com/alexansaa/vet_sql/assets/60579598/7dd512df-f797-42d1-a9c1-dd79260a84f0)
--Inside a transaction, update the animals table by setting the species column to digimon for all animals that have a name ending in mon.
![image](https://github.com/alexansaa/vet_sql/assets/60579598/4633b0ff-37dd-4230-b311-28e7e3c898de)
--Update the animals table by setting the species column to pokemon for all animals that don't have species already set.
![image](https://github.com/alexansaa/vet_sql/assets/60579598/28a09350-9aa0-4a7c-960b-d640a990201c)
--Commit the transaction. Verify that changes persist after commit.
![image](https://github.com/alexansaa/vet_sql/assets/60579598/2a9db49c-009b-428f-9eba-4622ab517562)
--Inside a transaction delete all records in the animals table.
![image](https://github.com/alexansaa/vet_sql/assets/60579598/3c62e7d6-8aec-48be-98aa-deeada11e34a)
--Then roll back the transaction. After the rollback verify if all records in the animals table still exists.
![image](https://github.com/alexansaa/vet_sql/assets/60579598/816e72df-4543-49e3-9885-14f4c1a84d06)
--Inside a transaction. Delete all animals born after Jan 1st, 2022.
![image](https://github.com/alexansaa/vet_sql/assets/60579598/78a7581a-132e-443a-8daa-11ed011946b6)
--Create a savepoint for the transaction.
![image](https://github.com/alexansaa/vet_sql/assets/60579598/7cd8aa75-ba7a-4444-9e76-db5da039eb59)
--Update all animals' weight to be their weight multiplied by -1.
![image](https://github.com/alexansaa/vet_sql/assets/60579598/5277fab8-ccfe-41ee-b45d-6746d14ad3c6)
--Rollback to the savepoint
![image](https://github.com/alexansaa/vet_sql/assets/60579598/22d5ed65-0730-483d-9f8f-efed3f98c78c)
![image](https://github.com/alexansaa/vet_sql/assets/60579598/4ffd7872-6d6c-47e1-8589-b5b5bb1466d5)
--Update all animals' weights that are negative to be their weight multiplied by -1.
![image](https://github.com/alexansaa/vet_sql/assets/60579598/f73bd56f-c560-4c5f-aa19-87c6d406dc8f)
![image](https://github.com/alexansaa/vet_sql/assets/60579598/4563b01a-c986-4012-abc3-2af3745673fe)
--Commit transaction
![image](https://github.com/alexansaa/vet_sql/assets/60579598/cb7ee5ba-ddb6-4fe3-a3c3-aada9186c282)
![image](https://github.com/alexansaa/vet_sql/assets/60579598/8649dad9-087c-4d23-a72e-4d7ffa5ce50f)

--Write queries to answer the following questions:
--How many animals are there?
![image](https://github.com/alexansaa/vet_sql/assets/60579598/e42f64d8-7d17-42a6-a3ba-11395989feed)
--How many animals have never tried to escape?
![image](https://github.com/alexansaa/vet_sql/assets/60579598/1c9888c6-86ed-4d71-9ba8-3de3d542d7e2)
--What is the average weight of animals?
![image](https://github.com/alexansaa/vet_sql/assets/60579598/9575c87d-ceda-4371-aeaa-83ba9267cd30)
--Who escapes the most, neutered or not neutered animals?
![image](https://github.com/alexansaa/vet_sql/assets/60579598/8ac7abca-8521-445b-ae11-a67160596ba9)
--What is the minimum and maximum weight of each type of animal?
![image](https://github.com/alexansaa/vet_sql/assets/60579598/d14a9d82-652f-4d0f-a4b5-26e42f0d5f07)
--What is the average number of escape attempts per animal type of those born between 1990 and 2000?
![image](https://github.com/alexansaa/vet_sql/assets/60579598/2ef63ca9-79a5-434c-84b2-b47231ac2129)

2023-10-03 15:51 UTC, topeogunleye requested changes
Hi @alexansaa, 

Good job so far!, Amazing SQL Explorer! 🚀🔍,
Big applause to you for diving deep into the SQL oceans and retrieving pearls of wisdom! 🌊🐚 Your contributions to both schema.sql and data.sql were on-point and followed the project guidelines beautifully. 

![Try-Again](https://user-images.githubusercontent.com/52934128/180646051-aed7efa6-6d15-4853-9962-73186e366f2c.gif)

### Highlight Review 🌟
#### Triumph in `schema.sql` 🏛️✨
- **Exquisite Addition to Schema:** 🧱📜 Your addition of a new `species` column with appropriate datatype and size is impeccable! Your choice of `varchar(255)` caters well to our use-case, providing ample space for varied species names while keeping data storage in check. 🌈🐾
```sql
ALTER TABLE animals ADD species varchar(255);
```

#### Mastery in `data.sql` 📊🌸
- **Perfect Data Insertions:** 🍀🚀 You have successfully inserted the given data into the `animals` table! Your meticulousness in adhering to the provided data and ensuring each value is in its rightful place demonstrates a keen eye for detail and a robust understanding of `INSERT` operations.
```sql
INSERT INTO animals (name, date_of_birth, escape_attempts, neutered, weight_kg)
VALUES ('Charmander', '2020/2/8', '0', 'false', '-11.0'),
       ('Plantmon', '2021/11/15', '2', 'true', '-5.7'),
       ('Squirtle', '1993/04/02', '3', 'false', '-12.13'),
       ('Angemon', '2005/06/12', '1', 'true', '-45.0'),
       ('Boarmon', '2005/06/07', '7', 'true', '20.4'),
       ('Blossom', '1998/10/13', '3', 'true', '17.0'),
       ('Ditto', '2022/05/14', '4', 'true', '22.0');
```
- **Efficient Batch Insertion:** 🚅📬 Your usage of a single `INSERT INTO` statement to populate multiple records demonstrates an understanding of efficient querying and effective database interaction. This is a noteworthy practice that minimizes server requests and optimizes transaction time!

#### Encouraging Words 🎉💖
Your progression and application of SQL commands in this project have been superb! 🚀🌟 By perfectly aligning your code with the project requirements, you’ve illustrated a beautiful synthesis of comprehension and application in the SQL universe! 🌌🗝️

Always remember: Your journey in the technological world is not just about acquiring knowledge, but also about celebrating every small victory along the way - just like today! 🌟🚀 Keep the curiosity alive, continue exploring, and never forget to bask in the joy of your accomplishments! 🌈🏆

Cheers to your amazing work and to the many more successes that await you on your learning adventure! 🎊🚀

### End of Highlight Review 🎈📚

Ready to sail towards new horizons? Let’s continue navigating through the sea of knowledge together! 🌊🚢📘

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Please kindly check my inline comments.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-03 15:51 UTC, topeogunleye commented on data.sql
> +VALUES ('Charmander', '2020-02-08', 0, false, -11.0, 'Unknown');
👋 Hello @alexansaa,

Your SQL statements are on the right track in terms of inserting into the animal's tables based on the conditions provided in the project requirements. However, there's a couple of discrepancies between your SQL insertion command and the project requirements that need to be addressed:

📌 **Typo in Column Name:** ❌ 
- You've used `nautered` instead of the required `neutered`. It's crucial to ensure column names are spelled correctly to avoid errors.

📌 **Additional Column:** ❌ 
- The addition of the `species` column in the INSERT statement does not align with the provided instructions. 

Here's how the adjusted code might look based on the project requirements:

```sql
INSERT INTO animals (name, date_of_birth, escape_attempts, neutered, weight_kg)
VALUES ('Charmander', '2020/02/08', 0, false, -11.0);
```

Please kindly make the changes to the remaining insertions into the animals table.

A Friendly Tip: 💡 Always make sure to thoroughly re-read the project requirements before diving into coding. Aligning your thought process with the objectives will set you on a straight path towards accurate and efficient solutions! 🎯🧠

Please feel free to explore, revise, and ask anything - I’m here for all your questions and to cheer you on! 🤗🎈

2023-10-03 15:51 UTC, topeogunleye commented on queries.sql
> +ROLLBACK;
Hello 👋,

Great job on tackling the SQL transaction assignment! Your code adheres largely to the project requirements and demonstrates a clear understanding of SQL transactions and UPDATE statements.  However, there are some subtle points that need your attention to strictly adhere to the project requirements. Let’s dive in:

#### 1. Verifying Changes:
The project requirements explicitly ask for a verification step after the rollback to ensure the data was reverted back. This is crucial to confirm that the rollback was successful and no data was unintentionally modified.


#### 3. Redundancy in Code: [OPTIONAL]
  You used an `END;` statement at the conclusion of your code which is unnecessary after `COMMIT;` in most SQL dialects.

- **Suggestion:** 🛠️ 
  Ensure to use only necessary statements in your code to keep it clean and efficient. Unless you're using a specific SQL dialect that requires it, the `END;` statement can be omitted.




Here's a slightly refined version of your code considering the above points:

```sql
-- Start a transaction
BEGIN;

-- Update the "species" column for all animals to "unspecified"
UPDATE animals
SET species = 'unspecified';

-- Verify the change by selecting the updated data
SELECT species FROM animals;

-- Roll back the transaction to revert the update
ROLLBACK;

-- Verify that the changes were undone by selecting the data after the rollback
SELECT species FROM animals;
```

Keep Going! 🎉💪 The journey of coding comes with its twists and turns, and every attempt is a step towards becoming a SQL wizard! 🧙‍♂️💼 Your forward momentum is palpable, and with each iteration, you're unfolding more and more of your potential! 🌟🛤️

You've done a noteworthy job! Always ensure to test your code thoroughly and adhere to the project guidelines. Keep coding and exploring! 👨‍💻🚀

Warm regards,
Temitope

2023-10-03 15:51 UTC, topeogunleye commented on queries.sql
> +END;
Hello! 🚀

Nice effort on implementing the SQL transactions and updating the `animals` table based on the specified conditions! Your code is well-structured and mostly aligns with the project requirements. However, a few points could be enhanced to strictly comply with the instructions and to follow best practices in SQL transactions. Let’s review them together:

1. **Verification after Commit:**
   - It's essential to verify that the changes persist after committing the transaction, as indicated in the project requirements. This step ensures that the updates have been successfully applied and maintained in the database.
   
   Suggested addition:
   ```sql
   -- Verify that changes persist after commit
   SELECT species FROM animals;
   ```
   
3. [OPTIONAL] **Use of END;** 
   - Similarly to the previous review, using `END;` might be unnecessary or even incorrect depending on the SQL dialect you're using. Typically, transactions are started with `BEGIN;` and closed with either `COMMIT;` or `ROLLBACK;`.
   
   Suggested change:
   Remove the `END;` statement from the code block.

Considering these points, here’s a refined version of your code:

```sql
-- Start a transaction
BEGIN;

-- Update the "species" column to "digimon" for animals with names ending in "mon"
UPDATE animals
SET species = 'digimon'
WHERE name LIKE '%mon';

-- Update the "species" column to "pokemon" for animals without a species already set
UPDATE animals
SET species = 'pokemon'
WHERE species IS NULL OR species = '';

-- Verify the changes within the transaction
SELECT species FROM animals;

-- Commit the transaction
COMMIT;

-- Verify that changes persist after commit
SELECT species FROM animals;
```

In addition to strictly adhering to project requirements, it’s always a great idea to periodically verify the state of your data during transaction blocks, especially before a `COMMIT;` statement, to ensure data integrity and prevent unintended changes. 

Keep up the great work, and always aim for meticulous verification in your transaction logic to maintain data consistency! 💻📊

Feel free to get in touch if you have any further queries or need additional clarification on the feedback.

Happy coding! 🎉

2023-10-03 15:51 UTC, topeogunleye commented on queries.sql
> +END;
Hello! 🌟

You've done a notable job on creating a transaction to delete records from the `animals` table and then utilizing a rollback to undo those changes. Your syntax is correct and you have addressed the major steps outlined in the project requirements. Nonetheless, there are a few aspects we should discuss and revisit to ensure absolute compliance with the provided requirements and optimized SQL practices:

1. **Verification Method:**
   - The project example suggests utilizing `COUNT(*)` to verify the state before and after the rollback. This is a more efficient way of confirming the total number of records without retrieving all the data, especially in cases where the table might contain a large number of rows.
   
   Suggested change:
   ```sql
   --Verify all records in the animals table still exists
   SELECT COUNT(*) FROM animals;
   ```

3. **Use of END;:** [OPTIONAL]
   - Once again, it's crucial to note that the `END;` statement is not typically used to conclude transactions in most SQL dialects. The transaction is effectively closed once `COMMIT;` or `ROLLBACK;` is executed.

   Suggested change: [OPTIONAL]
   Remove the `END;` statement from your code.

Here’s a refined version of your code considering the above points:

```sql
-- Start a transaction
BEGIN;

-- Delete all records from the "animals" table
DELETE FROM animals;

-- Verify the deletion
SELECT COUNT(*) FROM animals;

-- Roll back the transaction to undo the deletion
ROLLBACK;

-- Verify that all records in the animals table still exist
SELECT COUNT(*) FROM animals;
```

Your commitment to adhering to the project requirements is commendable! Keep maintaining this diligence and always ensure to select the most efficient queries, particularly when verifying data states, to optimize performance and resource usage. 🚀💼

If there are any aspects of the feedback you'd like to discuss or if you have further questions, please don’t hesitate to reach out.

Happy coding! 🧑‍💻💡

2023-10-04 00:30 UTC, afanimartin approved these changes
Hi @alexansaa, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Changes made as requested

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

## Find me on slack
### Martin Afani

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-04 14:17 UTC, merged